In [1]:
# Mappings are a collection of objects that are stored by a key 
# Sequence stores objects by their relative position. 
# Mappings won't retain order since they have objects defined by a key.

In [3]:
# A Python dictionary consists of a key and then an associated value. 
# That value can be almost any Python object.

In [4]:
# Creating dictionary from our laptop example
sale_dict ={
    'Brand':'Dell'
    ,'RAM (in GB) ':8
    ,'SSD (in GB) ':512
    ,'Price (in $)':42490
}

In [5]:
sale_dict

{'Brand': 'Dell',
 'RAM (in GB) ': 8,
 'SSD (in GB) ': 512,
 'Price (in $)': 42490}

In [6]:
type(sale_dict)

dict

In [7]:
sale_dict ={{
    'Brand':'Dell'
    ,'RAM (in GB) ':8
    ,'SSD (in GB) ':512
    ,'Price (in $)':42490
},
    {
     'Brand':'Apple'
    ,'RAM (in GB) ':8
    ,'SSD (in GB) ':256
    ,'Price (in $)':84990       
},
    {
    'Brand':'Lenovo'
    ,'RAM (in GB) ':4
    ,'SSD (in GB) ':256
    ,'Price (in $)':19900
        
},
    {
    'Brand':'Apple'
    ,'RAM (in GB) ':8
    ,'SSD (in GB) ':512
    ,'Price (in $)':149900
        
}
}

TypeError: unhashable type: 'dict'

In [9]:
sale_dict.keys()

dict_keys(['Brand', 'RAM (in GB) ', 'SSD (in GB) ', 'Price (in $)'])

In [10]:
sale_dict.values

<function dict.values>

In [11]:
sales_dict.values()

NameError: name 'sales_dict' is not defined

In [12]:
sale_dict.values()

dict_values(['Dell', 8, 512, 42490])

In [13]:
sale_dict.items()

dict_items([('Brand', 'Dell'), ('RAM (in GB) ', 8), ('SSD (in GB) ', 512), ('Price (in $)', 42490)])

In [14]:
#dictionaries are very flexible in the data types they can hold
flex_dict={'key1':'hi','key2': [12,23,33],'key3':['item0','item1','item2'],'key4':63}

In [15]:
flex_dict

{'key1': 'hi',
 'key2': [12, 23, 33],
 'key3': ['item0', 'item1', 'item2'],
 'key4': 63}

In [16]:
flex_dict[1]

KeyError: 1

In [17]:
flex_dict['key1']

'hi'

In [18]:
flex_dict['key2']

[12, 23, 33]

In [19]:
flex_dict['key2'][0]

12

In [20]:
flex_dict['key2'][-1]

33

In [21]:
# Can then even call methods on that value
flex_dict['key3'][2].upper()

'ITEM2'

In [22]:
flex_dict

{'key1': 'hi',
 'key2': [12, 23, 33],
 'key3': ['item0', 'item1', 'item2'],
 'key4': 63}

In [23]:
# Dictionaries is mutable 
flex_dict['key4']='I am added here!'
flex_dict

{'key1': 'hi',
 'key2': [12, 23, 33],
 'key3': ['item0', 'item1', 'item2'],
 'key4': 'I am added here!'}

In [24]:
# Sets are an unordered collection of unique elements. We can construct them by using the set() function.
a= {1,2,3}

In [25]:
a

{1, 2, 3}

In [28]:
type(a)

set

In [29]:
a.add(1)

In [30]:
a

{1, 2, 3}

In [31]:
a.add(4)

In [32]:
a

{1, 2, 3, 4}

In [33]:
# We can cast a list with multiple repeat elements to a set to get the unique elements. 
# But note that there is no order in the set.
repeated_elements=[1,2,2,2,2,2,4,5,5,6,7,7,7]
set(repeated_elements)

{1, 2, 4, 5, 6, 7}

In [34]:
a[0]='Hello'

TypeError: 'set' object does not support item assignment

In [35]:
4<5<6

True

In [36]:
1<4 and 4<860

True

In [37]:
1<2 or 8>9

True

In [39]:
x=5
if x<6:
   print('It is less than 6')
else:
    print('It is greater or equal to 6')

It is less than 6


In [2]:
#Suppose a customer is planning to go on her dream vacation but has a limited budget. 
#Thus, her decision to buy is based on the condition that the price comes under her budget.

#Q. Write a code in Python that prints whether the customer can go for dream vacation or not based on her budget.

# define the budget price

budget = int(input('Enter your budget(in rupees): '))
cost_of_travelling= 300000
# if-else statement
if cost_of_travelling < budget:
    print('Congrats! You can go on your dream vacation')
elif cost_of_travelling==budget:
    print('Congrats! You can go on your dream vacation at the exact budget you have')
else:
    print("Sorry! Your dream vacation's budget is more than your budget")


KeyboardInterrupt: Interrupted by user

In [3]:
int(input('Enter your budget(in dollars): '))

Enter your budget(in dollars): 77777


77777

In [4]:
input()

777777


'777777'

In [5]:
int(input())

777777


777777

In [9]:
budget = int(input('Enter your budget(in dollars): '))
cost_of_travel = 300000
if cost_of_travel < budget:
    print('Congrats!')
else:
    print('Sorry next time!')

Enter your budget(in dollars): 300000
Sorry next time!


In [17]:
budget = int(input('Enter your budget(in dollars): '))
cost_of_travel = 300000
if cost_of_travel < budget:
    print('Congrats!')
elif cost_of_travel == budget: 
    print('Congrats! Your budget is same as cost of travel')
else:
    print('Sorry next time!')

Enter your budget(in dollars): 400000
Congrats!


In [15]:
cost_of_travel

300000

In [18]:
budget

400000

In [19]:
# For loop:
fruits=['cherry','mango','banana']
for x in fruits:
    print(x)
    x+=1

cherry


TypeError: can only concatenate str (not "int") to str

In [20]:
# For loop with list:
fruits=['cherry','mango','banana']
for x in fruits:
    print(x)

cherry
mango
banana


In [29]:
# For loop with string:
text = 'Data Analyst Role'
for x in text:
    print(x)

D
a
t
a
 
A
n
a
l
y
s
t
 
R
o
l
e


In [48]:
# Example: 
# If you want to determine the cost of purchasing Biryani from Swiggy, 
# you may be interested to know that Swiggy offers various discount coupons. 
# To calculate the price of Biryani after applying discounts of 5%, 10%, 15%, and 20%. 
# Instead of calculating the discounted prices multiple times, looping statements can be used to achieve this.


#Q. Write a code in Python that prints the discounted price for each of the above-mentioned discounts.

a=set(range(10))

print(a)

b=list(range(10))
print(b)


c=tuple(range(10))
print(c)


print(list(range(10)))

print(list(range(2,8)))

print(list(range(0,11,5)))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7]
[0, 5, 10]


In [49]:
list(range(5, 21, 5))

[5, 10, 15, 20]

In [57]:
# Biryani Price code
price=500
for x in range(5,21,5):
    discount=x*(price/100)
    new_price=price-discount
    print('The price after providing ', x, ' percent discount is Rs ', new_price)

The price after providing  5  percent discount is Rs  475.0
The price after providing  10  percent discount is Rs  450.0
The price after providing  15  percent discount is Rs  425.0
The price after providing  20  percent discount is Rs  400.0


In [60]:
# While loop:
x=1
while x<5:
    print(x)
    x+=1

1
2
3
4


In [61]:
x = 0

while x < 5:
    print('x is currently: ',x)
    print(' x is still less than 5, adding 1 to x')
    x+=1

x is currently:  0
 x is still less than 5, adding 1 to x
x is currently:  1
 x is still less than 5, adding 1 to x
x is currently:  2
 x is still less than 5, adding 1 to x
x is currently:  3
 x is still less than 5, adding 1 to x
x is currently:  4
 x is still less than 5, adding 1 to x


# NumPy

In [64]:
# pre-packaged set of codes containing useful functions and tools
# created by developers to help others to solve common problems in coding
# Numpy-> provide tools for array and matrices
# Pandas-> provides tools for working with dataframes

#Tell python to import numpy by:
import numpy as np   

In [65]:
#NumPy is a package in Python that helps you work with arrays and matrices, which are basically tables of numbers. 
#It provides many useful functions that make it easier to manipulate these arrays and do mathematical operations with them.

## NumPy Array
#A NumPy array is a data structure in Python that represents a table of elements, usually numbers, arranged in rows and columns.

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [67]:
some_lst=["I'm string",2]
some_lst

["I'm string", 2]

In [69]:
np.array(some_lst) #1-D

array(["I'm string", '2'], dtype='<U11')

In [70]:
np.array(["I'm string",2])

array(["I'm string", '2'], dtype='<U11')

In [72]:
#Notice what happened to 2 int in this case. It is now a string


#An array-> stores values of same data type. 
#Python lists can contain values corresponding to different data types,
# arrays in python can only contain values corresponding to the same data type. 
#We can create NumPy arrays by converting a list to an array.

np.array(some_lst)

array(["I'm string", '2'], dtype='<U11')

In [73]:
# Numpy arrays essentially come in two forms: vectors and matrices. 
# Vectors are strictly 1-d arrays
# matrices are 2-d (but you should note a matrix can still have only one row or one column).

#list of list


many_lst=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
many_lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [75]:
type(many_lst)

list

In [76]:
np.array(many_lst) #2D matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# You can determine if array is 1d or 2d by looking at number of brackets.

In [ ]:
## Methods in numpy
-----------------------------------
#While manually creating NumPy arrays is useful for small examples,there are many inbuilt NumPy methods 
#for creating arrays that can save you a lot of time and effort when working with larger datasets

#np.zeros()
#np.ones()
#np.arange()
#np.linspace()
#np.eye()
#np.min()
#np.max()
#np.sum()
#np.mean()
#np.dtype()


In [84]:
#np.zeros()                This method creates an array of zeros with a specified shape. 
np.zeros(5)                # 1d array of zeros with floats in result
#np.zeros(5,dtype=int)

array([0., 0., 0., 0., 0.])

In [85]:
np.zeros([5,6])            #2-D array of zeros #5 rows and 6 columns. You just need to specify the shape # 2d array of zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [86]:
#np.ones()               #1-D array of 1
np.ones(5)  

array([1., 1., 1., 1., 1.])

In [88]:
np.ones([5,10])           #2-D array of 1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [89]:
#np.arange()
#The np.arange() function returns an array with evenly spaced elements as per the interval
#start is included but stop is excluded. It has the following paramaters:
#start : start of interval range.default=0
#stop : end of interval range
#step : step size of interval. default=1

np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [91]:
np.arange(5)
#np.arange(5,15,2)
#np.arange(1,51,5)

array([0, 1, 2, 3, 4])

In [92]:
# What if you want to create a 2d array using arange.. Just use reshape method

twod_array= np.arange(1,51,5).reshape(2,5) # shape must make sense
twod_array

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46]])

In [93]:
twod_array= np.arange(1,51,5).reshape(2,6) # shape must make sense
twod_array

ValueError: cannot reshape array of size 10 into shape (2,6)

In [94]:
#np.linspace() returns numbers which are evenly distributed with respect to interval. 
#Here the start and stop both are included.It has the following parameters:
#start: start of interval range. By default start = 0
#stop: end of interval range
#num : No. of samples to generate. By default num = 50

np.linspace(1,5) #by default it is divided into 50 parts


array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [95]:
np.linspace(1,5,10) #by default it is divided into 50 parts, but here 10 parts is mentioned

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [96]:
#np.eye()

#array of identity matrix
#It returns a matrix with ones on the diagonal and zeros elsewhere


np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [102]:
#Find minimum ,maximum ,sum and mean data in array

a=np.arange(5,25)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [103]:
a.min()

5

In [104]:
a.max()

24

In [105]:
a.sum()

290

In [106]:
a.mean()

14.5

In [109]:
a.dtype

dtype('int32')

In [111]:
## NumPy Indexing and Slicing :               Similar to list

# Create 1d array
a=np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [112]:
a[1]

2

In [113]:
a[-1]

19

In [114]:
a[:4]

array([1, 2, 3, 4])

In [115]:
a[1:8:2]

array([2, 4, 6, 8])

In [116]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
# Create 2-D array
b=np.arange(1,21).reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# Extract 1st row
# Extract 1st column
#Extract 20 ~ Option 1
#Extract 20 ~ Option 2
#Extract 15

In [51]:
# Extract 1st row
b[0]

array([1, 2, 3, 4, 5])

In [53]:
# Extract 1st column
b[:,0]
#b[:][0]

array([ 1,  6, 11, 16])

In [128]:
#Extract 20 ~ Option 1
b[-1,-1]

20

In [122]:
#Extract 20 ~ Option 2
b[3][4]

20

In [123]:
#Extract 15
b[2][4]

15

In [124]:
b[-2][-1]

15

In [131]:
## Broadcasting
a = np.arange(1,25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [132]:
#Setting a value with index range (Broadcasting)
a[0:5] = 1000
a

array([1000, 1000, 1000, 1000, 1000,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24])

In [ ]:
# Note that it actually changed the original array hence it is good that we create the copy array and then do the manipulation

In [133]:
a_new=np.arange(1,25)
a_new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [134]:
# Create copy
a_new_copy= a_new.copy()
a_new_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [135]:
a_new_copy[0:5]=1000  #Setting a value with index range (Broadcasting)
a_new_copy
# Copy is affected

array([1000, 1000, 1000, 1000, 1000,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24])

In [136]:
a_new
# Original is not affected

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
## Selection
#how to use brackets for selection based off of comparison operators

In [137]:
a_new>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [138]:
a_new[a_new>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [139]:
# Print numbers greater than 5 and less than and equal to 10
a_new[a_new> 5 AND a_new <=10]

SyntaxError: invalid syntax (2515181335.py, line 2)

In [140]:
a_new[a_new> 5 & a_new <=10]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [141]:
a_new[(a_new> 5) & (a_new <=10)]

array([ 6,  7,  8,  9, 10])

In [143]:
a_new[(a_new> 5) | (a_new <=10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [147]:
## Other Operations

#Add
#Subtract
#Multiply

arr1= np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
arr2= np.arange(1,5)
arr2

array([1, 2, 3, 4])

In [149]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (9,) (4,) 

In [150]:
arr1+arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [151]:
arr1-arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [152]:
arr1*arr1

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [153]:
arr1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [1]:
# Pandas Series

# Pandas Series -> like a single column of an excel spreadsheet and each entry in a series corresponds to an individual row in the spreadsheet. 
# Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). 
# What differentiates the NumPy array from a Series?
# a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. 
# It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

In [2]:
# Import pandas
import numpy as np
import pandas as pd

In [3]:
# We can create Series using a list,numpy array, or dictionary:

# Using List
# price list of different chocolate
chocolate_price_lst = [55,25,75,40,90]
chocolate_price_lst

[55, 25, 75, 40, 90]

In [4]:
series_lst = pd.Series(chocolate_price_lst)
series_lst

0    55
1    25
2    75
3    40
4    90
dtype: int64

In [5]:
# Using numpy array
chocolate_price_array= np.array(chocolate_price_lst)
chocolate_price_array

array([55, 25, 75, 40, 90])

In [7]:
series_array= pd.Series(chocolate_price_array)
series_array

0    55
1    25
2    75
3    40
4    90
dtype: int32

In [8]:
# Using dictionary
chocolate_price_dict = {'Silk':55,'Nestle':25,'Amul':75,'Parle':40,'Ferrero':90}
chocolate_price_dict

{'Silk': 55, 'Nestle': 25, 'Amul': 75, 'Parle': 40, 'Ferrero': 90}

In [21]:
# converting the dictionary into a Pandas Series object
series_dict = pd.Series(chocolate_price_dict)
series_dict

Silk       55
Nestle     25
Amul       75
Parle      40
Ferrero    90
dtype: int64

In [14]:
#Alternative ways:
print(pd.Series([55,25,75,40,90])) # using list
print("\n")
print(pd.Series(np.array([55,25,75,40,90]))) # using numpy Array
print("\n")
print(pd.Series({'Silk':55,'Nestle':25,'Amul':75,'Parle':40,'Ferrero':90}))# using dictionary

0    55
1    25
2    75
3    40
4    90
dtype: int64


0    55
1    25
2    75
3    40
4    90
dtype: int32


Silk       55
Nestle     25
Amul       75
Parle      40
Ferrero    90
dtype: int64


In [15]:
# Even functions can be part of Series
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [ ]:
# Indexing using Index # Find element at 1 index or Nestle label
# Extract price of Amul
# Extract price of Amul & Parle
# adding 5 to existing prices

In [16]:
# Indexing using Index
series_dict[1]

25

In [17]:
series_dict['Nestle']

25

In [18]:
# Extract price of Amul
series_dict[2]

75

In [19]:
# Extract price of Amul & Parle
series_dict[2:4]

Amul     75
Parle    40
dtype: int64

In [22]:
# adding 5 to existing prices
series_dict_updated=series_dict+5
series_dict_updated

Silk       60
Nestle     30
Amul       80
Parle      45
Ferrero    95
dtype: int64

In [ ]:
### Pandas Dataframe

# A DataFrame is a two-dimensional table-like data structure in Pandas that consists of rows and columns
# DataFrame is a bunch of Series objects put together to share the same index. 
# In a DataFrame, each column can have a different data type, such as numbers, strings, or dates, 
# and each row represents a unique record or observation. 
# The rows and columns are labeled for easy indexing and selection.

In [26]:
# Let us create Dataframe using Dict
cust_data = {'CustomerID':['ROLEID100','ROLEID101','ROLEID102','ROLEID103','ROLEID104'],
             'location':['Mumbai', 'Bengaluru', 'Bengaluru', 'Kolkata', 'Surat'],
             'gender':['M','F','F','M','F'],
             'education':['MBA','MSc','Bcom','BA','MBBS'],
             'age':[25,35,35,18,26],
             'no. of years of experience':[2,9,9,0,2]    
}
cust_data

{'CustomerID': ['ROLEID100',
  'ROLEID101',
  'ROLEID102',
  'ROLEID103',
  'ROLEID104'],
 'location': ['Mumbai', 'Bengaluru', 'Bengaluru', 'Kolkata', 'Surat'],
 'gender': ['M', 'F', 'F', 'M', 'F'],
 'education': ['MBA', 'MSc', 'Bcom', 'BA', 'MBBS'],
 'age': [25, 35, 35, 18, 26],
 'no. of years of experience': [2, 9, 9, 0, 2]}

In [27]:
# creating the dataframe using dictionary
workshop_data= pd.DataFrame(cust_data)
workshop_data

CustomerID   location gender education  age  no. of years of experience
0  ROLEID100     Mumbai      M       MBA   25                           2
1  ROLEID101  Bengaluru      F       MSc   35                           9
2  ROLEID102  Bengaluru      F      Bcom   35                           9
3  ROLEID103    Kolkata      M        BA   18                           0
4  ROLEID104      Surat      F      MBBS   26                           2

In [ ]:
#There are several ways to convert data into a Pandas DataFrame. Here are some common methods:

# 1. From a CSV or Excel file: You can use the read_csv() or read_excel() functions in Pandas to read data from a CSV or Excel
#    file and convert it into a DataFrame.
# 2. From a Python dictionary: You can create a Python dictionary with the data and pass it to the DataFrame() constructor to create a DataFrame.
# 3. From a NumPy array: You can create a NumPy array with the data and pass it to the DataFrame() constructor to create a DataFrame.
# 4. From a SQL database: You can use the read_sql() function in Pandas to read data from a SQL database and convert it into a DataFrame.


In [29]:
## Access data from Dataframe
# Access last column i.e. no of years of experience
# accessing first column of the dataframe using the row label
# accessing first column of the dataframe using integer position and iloc
# accessing first row of the dataframe using loc and iloc
# first and second columns ~ Option 1 using iloc
# first and second columns ~ Option 2 using loc
# accessing selected rows and columns using iloc method 

In [30]:
# Access last column i.e. no of years of experience
# accessing first column of the dataframe using the row label
workshop_data['no. of years of experience']

0    2
1    9
2    9
3    0
4    2
Name: no. of years of experience, dtype: int64

In [33]:
# accessing first column of the dataframe using integer position
workshop_data[1] #error

KeyError: 1

In [34]:
#Using loc and iloc method

#The loc method in pandas allows you to access rows and columns using their index labels dataframe.
#loc[row selection, column selection]
#iloc method allows you to access rows and columns using their integer positions dataframe.
#iloc[row selection, column selection

# accessing first column of the dataframe using the row label
workshop_data['CustomerID']

0    ROLEID100
1    ROLEID101
2    ROLEID102
3    ROLEID103
4    ROLEID104
Name: CustomerID, dtype: object

In [41]:
# accessing first column of the dataframe using the row label and loc
workshop_data.loc[:,'CustomerID']

0    ROLEID100
1    ROLEID101
2    ROLEID102
3    ROLEID103
4    ROLEID104
Name: CustomerID, dtype: object

In [42]:
# accessing first column of the dataframe using integer position and iloc
workshop_data.iloc[:,0]

0    ROLEID100
1    ROLEID101
2    ROLEID102
3    ROLEID103
4    ROLEID104
Name: CustomerID, dtype: object

In [56]:
# accessing first row of the dataframe using loc and iloc
print(workshop_data.loc[0])
print("\n")
print(workshop_data.iloc[0])

CustomerID                    ROLEID100
location                         Mumbai
gender                                M
education                           MBA
age                                  25
no. of years of experience            2
Name: 0, dtype: object


CustomerID                    ROLEID100
location                         Mumbai
gender                                M
education                           MBA
age                                  25
no. of years of experience            2
Name: 0, dtype: object


In [58]:
# first and second columns ~ Option 1 using iloc
workshop_data.iloc[:,:2]

CustomerID   location
0  ROLEID100     Mumbai
1  ROLEID101  Bengaluru
2  ROLEID102  Bengaluru
3  ROLEID103    Kolkata
4  ROLEID104      Surat

In [61]:
# first and second columns ~ Option 2 using loc
workshop_data.loc[:,['CustomerID','location']]

CustomerID   location
0  ROLEID100     Mumbai
1  ROLEID101  Bengaluru
2  ROLEID102  Bengaluru
3  ROLEID103    Kolkata
4  ROLEID104      Surat

In [64]:
# accessing selected rows and columns using iloc method access ROLEID101, ROLEID104 and gender 
workshop_data.iloc[[1,4],[0,2]]

CustomerID gender
1  ROLEID101      F
4  ROLEID104      F

In [65]:
### Conditional Selection
#An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

workshop_data


CustomerID   location gender education  age  no. of years of experience
0  ROLEID100     Mumbai      M       MBA   25                           2
1  ROLEID101  Bengaluru      F       MSc   35                           9
2  ROLEID102  Bengaluru      F      Bcom   35                           9
3  ROLEID103    Kolkata      M        BA   18                           0
4  ROLEID104      Surat      F      MBBS   26                           2

In [66]:
workshop_data['age']>25

0    False
1     True
2     True
3    False
4     True
Name: age, dtype: bool

In [67]:
# Extract CustomerID with age>25
workshop_data[workshop_data['age']>25]

CustomerID   location gender education  age  no. of years of experience
1  ROLEID101  Bengaluru      F       MSc   35                           9
2  ROLEID102  Bengaluru      F      Bcom   35                           9
4  ROLEID104      Surat      F      MBBS   26                           2

In [69]:
# Extract CustomerID with age>25 and location is Bengaluru
workshop_data[(workshop_data['age']>25) & (workshop_data['location']=='Bengaluru')]

CustomerID   location gender education  age  no. of years of experience
1  ROLEID101  Bengaluru      F       MSc   35                           9
2  ROLEID102  Bengaluru      F      Bcom   35                           9

In [ ]:
### Treating Missing Values
# Missing values are a common problem in data analysis and can cause errors in computations and analysis. 
# Pandas is a popular Python library for data manipulation and analysis 
# that provides many tools for handling missing values in a DataFrame.
# In Pandas, missing values are represented by the special value NaN (Not a Number). 

# Pandas provides several methods for detecting and handling missing values, including:
# isnull() method: returns a Boolean mask indicating missing values in a DataFrame
# dropna() method: removes rows or columns with missing values
# fillna() method: fills missing values with a specified value or method such as forward filling, 
#                  backward filling or mean imputation.

In [72]:
# np.nan is a special value in NumPy that represents a missing or undefined value. The term "nan" stands for "Not a Number"
np.nan

nan

In [73]:
np.nan==np.nan # Fun fact np.nan is a unique value in that it does not compare equal to any other value, including itself. 

False

In [74]:
# Create DataFrame with null values
df = pd.DataFrame({'StudentName':['Arfa', 'Kiana', 'Pratik', 'Laksh','Ray'],
                   'Years_of_experience':[6, np.nan, np.nan, 9, 10],
                   'Age':[27, 28, np.nan, 30, 35],
                   'Years_of_experience_in_data':[3, np.nan, np.nan,np.nan,4] 
})
df

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
1       Kiana                  NaN  28.0                          NaN
2      Pratik                  NaN   NaN                          NaN
3       Laksh                  9.0  30.0                          NaN
4         Ray                 10.0  35.0                          4.0

In [75]:
#View the data 

df.head()

# df.head(n) is a method in Pandas that allows you to preview the first n rows of a DataFrame, 
# where n is the number of rows you specify as an argument. 
# By default, it returns the first five rows of the DataFrame.

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
1       Kiana                  NaN  28.0                          NaN
2      Pratik                  NaN   NaN                          NaN
3       Laksh                  9.0  30.0                          NaN
4         Ray                 10.0  35.0                          4.0

In [76]:
df.head(2)

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
1       Kiana                  NaN  28.0                          NaN

In [77]:
# Check for null values
df.isnull()

StudentName  Years_of_experience    Age  Years_of_experience_in_data
0        False                False  False                        False
1        False                 True  False                         True
2        False                 True   True                         True
3        False                False  False                         True
4        False                False  False                        False

In [79]:
# Now that we know there is null values we can either drop/ replace the null values. 
# First let us look at how to drop the null values
# Drop rows with any missing values
df.dropna()

# Notice how it dropped every row which has null. This dropna() works rows wise by default
# Lets understand the axis, thresh, and inplace

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
4         Ray                 10.0  35.0                          4.0

In [80]:
df.dropna(axis=1) # It dropped every column which has null values

StudentName
0        Arfa
1       Kiana
2      Pratik
3       Laksh
4         Ray

In [81]:
df

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
1       Kiana                  NaN  28.0                          NaN
2      Pratik                  NaN   NaN                          NaN
3       Laksh                  9.0  30.0                          NaN
4         Ray                 10.0  35.0                          4.0

In [85]:
df.dropna(thresh=2)
# The thresh parameter specifies the minimum number of non-null values required for a row or column to be kept.
# In this case python will drop the row where there is 3 or higher null values

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
1       Kiana                  NaN  28.0                          NaN
3       Laksh                  9.0  30.0                          NaN
4         Ray                 10.0  35.0                          4.0

In [87]:
df_new = df.copy()
df_new

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
1       Kiana                  NaN  28.0                          NaN
2      Pratik                  NaN   NaN                          NaN
3       Laksh                  9.0  30.0                          NaN
4         Ray                 10.0  35.0                          4.0

In [88]:
df.dropna()

#notice how dropped rows are retained

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
4         Ray                 10.0  35.0                          4.0

In [89]:
df 

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
1       Kiana                  NaN  28.0                          NaN
2      Pratik                  NaN   NaN                          NaN
3       Laksh                  9.0  30.0                          NaN
4         Ray                 10.0  35.0                          4.0

In [90]:
df_new.dropna(inplace=True)

In [91]:
df_new #Notice how it has dropped the rows in reality

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
4         Ray                 10.0  35.0                          4.0

In [95]:
# Fill missing values with a specific value
df.fillna(value='')

StudentName Years_of_experience   Age Years_of_experience_in_data
0        Arfa                 6.0  27.0                         3.0
1       Kiana                      28.0                            
2      Pratik                                                      
3       Laksh                 9.0  30.0                            
4         Ray                10.0  35.0                         4.0

In [96]:
df.fillna(value=df.mean())

C:\Users\dhill\AppData\Local\Temp\ipykernel_17516\1364442528.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(value=df.mean())


StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa             6.000000  27.0                          3.0
1       Kiana             8.333333  28.0                          3.5
2      Pratik             8.333333  30.0                          3.5
3       Laksh             9.000000  30.0                          3.5
4         Ray            10.000000  35.0                          4.0

In [107]:
#Fill na for specific column
df['Age'].fillna(value=df['Age'].mean())
df

StudentName  Years_of_experience   Age  Years_of_experience_in_data
0        Arfa                  6.0  27.0                          3.0
1       Kiana                  NaN  28.0                          NaN
2      Pratik                  NaN   NaN                          NaN
3       Laksh                  9.0  30.0                          NaN
4         Ray                 10.0  35.0                          4.0

In [26]:
### Groupby: 
# In Pandas, groupby is a powerful method for grouping and aggregating data in a DataFrame based on one or more columns.

# create a DataFrame of Indian brands with their sales data
df = pd.DataFrame({ 'brand':['Tata', 'Reliance', 'Mahindra', 'Hindustan Unilever', 'Tata', 'Reliance', 'Hindustan Unilever','Mahindra'],
                   'salesperson':['Amit', 'Rahul', 'Riya', 'Amay', 'Rohan', 'Ritika', 'Aditya', 'Ronak'],
                   'sales':[15000, 20000, 10000, 30000, 25000, 15000, 35000, 40000]   
})

df

brand salesperson  sales
0                Tata        Amit  15000
1            Reliance       Rahul  20000
2            Mahindra        Riya  10000
3  Hindustan Unilever        Amay  30000
4                Tata       Rohan  25000
5            Reliance      Ritika  15000
6  Hindustan Unilever      Aditya  35000
7            Mahindra       Ronak  40000

In [27]:
group = df.groupby('brand')
group

In [28]:
group.mean()

sales
brand                      
Hindustan Unilever  32500.0
Mahindra            25000.0
Reliance            17500.0
Tata                20000.0

In [29]:
df.groupby('brand').sum()

sales
brand                    
Hindustan Unilever  65000
Mahindra            50000
Reliance            35000
Tata                40000

In [30]:
df.groupby('brand').std()

sales
brand                           
Hindustan Unilever   3535.533906
Mahindra            21213.203436
Reliance             3535.533906
Tata                 7071.067812

In [31]:
df.groupby('brand').min()

salesperson  sales
brand                                
Hindustan Unilever      Aditya  30000
Mahindra                  Riya  10000
Reliance                 Rahul  15000
Tata                      Amit  15000

In [32]:
df.groupby('brand').max()

salesperson  sales
brand                                
Hindustan Unilever        Amay  35000
Mahindra                 Ronak  40000
Reliance                Ritika  20000
Tata                     Rohan  25000

In [33]:
df.describe() 
# The describe() method in Pandas is used to generate descriptive statistics of a DataFrame (Only numeric columns).

sales
count      8.000000
mean   23750.000000
std    10606.601718
min    10000.000000
25%    15000.000000
50%    22500.000000
75%    31250.000000
max    40000.000000

In [34]:
### Other important operators

df['brand'].unique() #array of unique values

array(['Tata', 'Reliance', 'Mahindra', 'Hindustan Unilever'], dtype=object)

In [35]:
df['salesperson'].unique()

array(['Amit', 'Rahul', 'Riya', 'Amay', 'Rohan', 'Ritika', 'Aditya',
       'Ronak'], dtype=object)

In [36]:
df['sales'].unique()

array([15000, 20000, 10000, 30000, 25000, 35000, 40000], dtype=int64)

In [37]:
df['brand'].nunique() # no.of unique values in the column

4

In [38]:
df['sales'].nunique()

7

In [39]:
df.columns

Index(['brand', 'salesperson', 'sales'], dtype='object')

In [40]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [41]:
df['brand'].value_counts()


Tata                  2
Reliance              2
Mahindra              2
Hindustan Unilever    2
Name: brand, dtype: int64

In [46]:
df['sales'].value_counts()

15000    2
20000    1
10000    1
30000    1
25000    1
35000    1
40000    1
Name: sales, dtype: int64

In [42]:
df['sales'].sum()

190000

In [47]:
df.sort_values(by='brand') #ascending is true by default

brand salesperson  sales
3  Hindustan Unilever        Amay  30000
6  Hindustan Unilever      Aditya  35000
2            Mahindra        Riya  10000
7            Mahindra       Ronak  40000
1            Reliance       Rahul  20000
5            Reliance      Ritika  15000
0                Tata        Amit  15000
4                Tata       Rohan  25000

In [48]:
df.sort_values(by='sales') #ascending is true by default

brand salesperson  sales
2            Mahindra        Riya  10000
0                Tata        Amit  15000
5            Reliance      Ritika  15000
1            Reliance       Rahul  20000
4                Tata       Rohan  25000
3  Hindustan Unilever        Amay  30000
6  Hindustan Unilever      Aditya  35000
7            Mahindra       Ronak  40000

In [49]:
df.pivot_table(values='sales' ,index=['salesperson'], columns=['brand'])

brand        Hindustan Unilever  Mahindra  Reliance     Tata
salesperson                                                 
Aditya                  35000.0       NaN       NaN      NaN
Amay                    30000.0       NaN       NaN      NaN
Amit                        NaN       NaN       NaN  15000.0
Rahul                       NaN       NaN   20000.0      NaN
Ritika                      NaN       NaN   15000.0      NaN
Riya                        NaN   10000.0       NaN      NaN
Rohan                       NaN       NaN       NaN  25000.0
Ronak                       NaN   40000.0       NaN      NaN

In [50]:
# Permanently delete the column
del df['sales']

In [51]:
df

brand salesperson
0                Tata        Amit
1            Reliance       Rahul
2            Mahindra        Riya
3  Hindustan Unilever        Amay
4                Tata       Rohan
5            Reliance      Ritika
6  Hindustan Unilever      Aditya
7            Mahindra       Ronak